name: "Kafka CLI Tools Mastery"
modules:
  activate:
  - 00-workshop-overview
  - 01-cli-introduction
  - 02-kafka-topics
  - 03-kafka-console-producer
  - 04-kafka-console-consumer
  - 05-kafka-consumer-groups
  - 06-kafka-reassign-partitions
  - 07-kafka-log-dirs
  - 08-kafka-configs
exit_sign: "Finish"
